### ISSUE TITLE
Training with only FlyingChairs dataset.

### ISSUE THREAD

**Issue by AlbertHuyb** [hellochick/PWCNet-tf2#9]
As the `optical_flow` folder of FlyingThings3D is too large to download, I try to train PWCNet-tf2 with only FlyingChairs dataset. Do you have any suggestions for parameter settings? Will it hurt the performance in a big way?

Thanks for your help.

**Comment by hellochick** [comment]
Hi @AlbertHuyb ,

Since the scale of the flow differs a lot between FlyingChairs and FlyingThings3D datasets, it will affect the performance a lot.
FlyingChairs dataset only covers small motions, while FlyingThings3D covers large motions.

So I will recommend training on both datasets if possible, or loading the pre-trained models.

**Comment by AlbertHuyb** [comment]
Thank you for your helpful answer, then I'll close this issue.
